In [1]:
import os
os.chdir("..")

import sys
sys.path.append("src")

import pandas as pd

from wildfire_gnn.pipelines.cnn_baseline_pipeline import CNNBaselinePipeline
from wildfire_gnn.utils.config import load_yaml_config

In [2]:
config = load_yaml_config("configs/cnn_baseline_config.yaml")
pipeline = CNNBaselinePipeline(config)

In [3]:
from pathlib import Path
import rasterio

paths = list(Path("data/interim/aligned").glob("*.img"))

for p in paths:
    with rasterio.open(p) as src:
        print(p.name, src.shape, src.dtypes, src.nodata)

Burn_Prob.img (7597, 7555) ('float32',) -9999.0
CFL.img (7597, 7555) ('float32',) -9999.0
FSP_Index.img (7597, 7555) ('float32',) -9999.0
Fuel_Models.img (7597, 7555) ('uint8',) 0.0
Ignition_Prob.img (7597, 7555) ('float32',) -9999.0
Struct_Exp_Index.img (7597, 7555) ('float32',) -9999.0

In [4]:
results_df = pipeline.run()
results_df

2026-04-02 18:32:57 | INFO | cnn_baseline_pipeline | Stratified bin [0.0, 0.01): available=5356465 sampled=40000
2026-04-02 18:32:58 | INFO | cnn_baseline_pipeline | Stratified bin [0.01, 0.05): available=4727847 sampled=40000
2026-04-02 18:32:59 | INFO | cnn_baseline_pipeline | Stratified bin [0.05, 0.1): available=1160219 sampled=40000
2026-04-02 18:32:59 | INFO | cnn_baseline_pipeline | Stratified bin [0.1, 0.25): available=507855 sampled=40000
2026-04-02 18:32:59 | INFO | cnn_baseline_pipeline | Stratified bin [0.25, 1.0): available=16 sampled=16
2026-04-02 18:33:04 | INFO | cnn_baseline_pipeline | Applied stratified subsampling: kept 200000 / 11752402 patches
2026-04-02 18:33:06 | INFO | cnn_baseline_pipeline | Saved patch metadata to data/processed/cnn_patch_metadata.csv
2026-04-02 18:33:06 | INFO | cnn_baseline_pipeline | CNN dataset stats: original_samples=11752402 sampled_samples=200000 target_min=0.000000 target_max=0.250882 target_mean=0.052204 target_std=0.053710
2026-04-02 18:33:11 | INFO | cnn_baseline_pipeline | Saved random CNN splits to data/processed/cnn_splits_random.npz
2026-04-02 18:33:12 | INFO | cnn_baseline_pipeline | Saved spatial CNN splits to data/processed/cnn_splits_spatial.npz
2026-04-02 18:33:12 | INFO | cnn_baseline_pipeline | [random] train=140000 val=30000 test=30000
2026-04-02 18:35:47 | INFO | cnn_baseline_pipeline | [random] epoch=1 train_loss=0.001962 val_loss=0.001263
2026-04-02 18:39:55 | INFO | cnn_baseline_pipeline | [random] epoch=2 train_loss=0.000720 val_loss=0.000639
2026-04-02 18:45:32 | INFO | cnn_baseline_pipeline | [random] epoch=3 train_loss=0.000678 val_loss=0.000669
2026-04-02 18:50:05 | INFO | cnn_baseline_pipeline | [random] epoch=4 train_loss=0.000659 val_loss=0.000622
2026-04-02 18:53:46 | INFO | cnn_baseline_pipeline | [random] epoch=5 train_loss=0.000653 val_loss=0.000571
2026-04-02 18:59:17 | INFO | cnn_baseline_pipeline | [random] epoch=6 train_loss=0.000616 val_loss=0.000564
2026-04-02 19:05:06 | INFO | cnn_baseline_pipeline | [random] epoch=7 train_loss=0.000573 val_loss=0.000754
2026-04-02 19:13:24 | INFO | cnn_baseline_pipeline | [random] epoch=8 train_loss=0.000563 val_loss=0.000572
2026-04-02 19:17:18 | INFO | cnn_baseline_pipeline | [random] epoch=9 train_loss=0.000555 val_loss=0.000539
2026-04-02 19:23:10 | INFO | cnn_baseline_pipeline | [random] epoch=10 train_loss=0.000544 val_loss=0.000548
2026-04-02 19:24:28 | INFO | cnn_baseline_pipeline | [random] epoch=11 train_loss=0.000540 val_loss=0.000530
2026-04-02 19:31:09 | INFO | cnn_baseline_pipeline | [random] epoch=12 train_loss=0.000540 val_loss=0.000510
2026-04-02 19:37:37 | INFO | cnn_baseline_pipeline | [random] epoch=13 train_loss=0.000524 val_loss=0.000900
2026-04-02 19:40:39 | INFO | cnn_baseline_pipeline | [random] epoch=14 train_loss=0.000517 val_loss=0.002606
2026-04-02 19:41:40 | INFO | cnn_baseline_pipeline | [random] epoch=15 train_loss=0.000515 val_loss=0.004207
2026-04-02 19:41:53 | INFO | cnn_baseline_pipeline | [random] Validation metrics: {'rmse': 0.02257551120359323, 'mae': 0.015514523722231388, 'r2': 0.8194840550422668, 'pearson': 0.9122190475463867, 'spearman': 0.9315341795527632}
2026-04-02 19:41:53 | INFO | cnn_baseline_pipeline | [random] Test metrics: {'rmse': 0.02259323172210617, 'mae': 0.015525762923061848, 'r2': 0.8218045830726624, 'pearson': 0.9142122268676758, 'spearman': 0.9329583507120703}
2026-04-02 19:41:53 | INFO | cnn_baseline_pipeline | [spatial] train=140832 val=30582 test=28586
2026-04-02 19:42:56 | INFO | cnn_baseline_pipeline | [spatial] epoch=1 train_loss=0.001815 val_loss=0.001524
2026-04-02 19:44:09 | INFO | cnn_baseline_pipeline | [spatial] epoch=2 train_loss=0.000763 val_loss=0.000655
2026-04-02 19:45:16 | INFO | cnn_baseline_pipeline | [spatial] epoch=3 train_loss=0.000730 val_loss=0.001337
2026-04-02 19:46:25 | INFO | cnn_baseline_pipeline | [spatial] epoch=4 train_loss=0.000671 val_loss=0.000929
2026-04-02 19:51:54 | INFO | cnn_baseline_pipeline | [spatial] epoch=5 train_loss=0.000627 val_loss=0.000677
2026-04-02 19:56:48 | INFO | cnn_baseline_pipeline | [spatial] epoch=6 train_loss=0.000608 val_loss=0.010759
2026-04-02 19:56:48 | INFO | cnn_baseline_pipeline | [spatial] Early stopping at epoch 6
2026-04-02 19:57:01 | INFO | cnn_baseline_pipeline | [spatial] Validation metrics: {'rmse': 0.02559982825450731, 'mae': 0.020139440894126892, 'r2': 0.7051510214805603, 'pearson': 0.846233069896698, 'spearman': 0.8741011777331843}
2026-04-02 19:57:01 | INFO | cnn_baseline_pipeline | [spatial] Test metrics: {'rmse': 0.018483876959047775, 'mae': 0.015531470999121666, 'r2': 0.4875198006629944, 'pearson': 0.848472535610199, 'spearman': 0.800038359041351}
2026-04-02 19:57:01 | INFO | cnn_baseline_pipeline | Saved CNN metrics to reports\tables\cnn_metrics.csv

,model,split_type,data_split,rmse,mae,r2,pearson,spearman
0,cnn,random,val,0.022576,0.015515,0.819484,0.912219,0.931534
1,cnn,random,test,0.022593,0.015526,0.821805,0.914212,0.932958
2,cnn,spatial,val,0.025600,0.020139,0.705151,0.846233,0.874101
3,cnn,spatial,test,0.018484,0.015531,0.487520,0.848473,0.800038

In [5]:
metrics_df = pd.read_csv("reports/tables/cnn_metrics.csv")
metrics_df

,model,split_type,data_split,rmse,mae,r2,pearson,spearman
0,cnn,random,val,0.022576,0.015515,0.819484,0.912219,0.931534
1,cnn,random,test,0.022593,0.015526,0.821805,0.914212,0.932958
2,cnn,spatial,val,0.025600,0.020139,0.705151,0.846233,0.874101
3,cnn,spatial,test,0.018484,0.015531,0.487520,0.848473,0.800038

In [6]:
cnn_random_preds = pd.read_csv("reports/tables/cnn_random_test_predictions.csv")
cnn_random_preds.head()

   row_index  col_index    y_true    y_pred  residual
0       4756       2197  0.088232  0.085811  0.002421
1       3728       2555  0.175064  0.089820  0.085244
2       1527       1837  0.122934  0.092039  0.030895
3       4296       2558  0.064533  0.056204  0.008329
4       1566       2981  0.047159  0.078844 -0.031685

In [7]:
cnn_spatial_preds = pd.read_csv("reports/tables/cnn_spatial_test_predictions.csv")
cnn_spatial_preds.head()

   row_index  col_index    y_true    y_pred  residual
0       4890       1812  0.019513  0.030981 -0.011469
1       1587       2502  0.033439  0.056645 -0.023205
2        846       3546  0.003566  0.031047 -0.027481
3       2531       1205  0.005752  0.022612 -0.016861
4       2201       1277  0.000667  0.017680 -0.017013