In [1]:
import os
os.chdir("..")

import sys
sys.path.append("src")

import pandas as pd

from wildfire_gnn.pipelines.gnn_pipeline import run_gnn_pipeline
from wildfire_gnn.utils.config import load_yaml_config

In [2]:

config = load_yaml_config("configs/gnn_config.yaml")
metrics = run_gnn_pipeline(config)
metrics

Epoch 001 | Train Loss: 0.069462 | Val Loss: 0.001078
Epoch 002 | Train Loss: 0.045678 | Val Loss: 0.001242
Epoch 003 | Train Loss: 0.038587 | Val Loss: 0.001435
Epoch 004 | Train Loss: 0.036258 | Val Loss: 0.001509
Epoch 005 | Train Loss: 0.036281 | Val Loss: 0.001442
Epoch 006 | Train Loss: 0.034466 | Val Loss: 0.001280
Epoch 007 | Train Loss: 0.032442 | Val Loss: 0.001114
Epoch 008 | Train Loss: 0.028209 | Val Loss: 0.001048
Epoch 009 | Train Loss: 0.026410 | Val Loss: 0.001138
Epoch 010 | Train Loss: 0.026742 | Val Loss: 0.001353
Epoch 011 | Train Loss: 0.024889 | Val Loss: 0.001601
Epoch 012 | Train Loss: 0.025844 | Val Loss: 0.001789
Epoch 013 | Train Loss: 0.025098 | Val Loss: 0.001870
Epoch 014 | Train Loss: 0.024013 | Val Loss: 0.001846
Epoch 015 | Train Loss: 0.022444 | Val Loss: 0.001757
Epoch 016 | Train Loss: 0.021445 | Val Loss: 0.001664
Epoch 017 | Train Loss: 0.020352 | Val Loss: 0.001613
Epoch 018 | Train Loss: 0.019520 | Val Loss: 0.001621
Epoch 019 | Train Loss: 0.019152 | Val Loss: 0.001671
Epoch 020 | Train Loss: 0.018398 | Val Loss: 0.001727
Epoch 021 | Train Loss: 0.019455 | Val Loss: 0.001747
Epoch 022 | Train Loss: 0.017995 | Val Loss: 0.001716
Epoch 023 | Train Loss: 0.018312 | Val Loss: 0.001637
Epoch 024 | Train Loss: 0.016409 | Val Loss: 0.001537
Epoch 025 | Train Loss: 0.016035 | Val Loss: 0.001447
Epoch 026 | Train Loss: 0.015675 | Val Loss: 0.001393
Epoch 027 | Train Loss: 0.015370 | Val Loss: 0.001386
Epoch 028 | Train Loss: 0.014946 | Val Loss: 0.001411
Early stopping triggered.

{'train': {'rmse': 0.04007774612645505,
  'mae': 0.028123488649725914,
  'r2': -0.4632457494735718,
  'pearson': 0.13104328513145447,
  'spearman': 0.11573787697498866,
  'ece_reg': nan,
  'coverage_95': nan},
 'val': {'rmse': 0.03237195523753176,
  'mae': 0.022692760452628136,
  'r2': -1.5785300731658936,
  'pearson': 0.15106433629989624,
  'spearman': 0.15333424250697214,
  'ece_reg': nan,
  'coverage_95': nan},
 'test': {'rmse': 0.04585750509816933,
  'mae': 0.031936321407556534,
  'r2': -0.28819477558135986,
  'pearson': 0.10316810756921768,
  'spearman': 0.04410948461411081,
  'ece_reg': nan,
  'coverage_95': nan}}

In [3]:
metrics_df = pd.read_csv("reports/tables/gnn_metrics.csv")
metrics_df.tail()

,model,split_type,data_split,rmse,mae,r2,pearson,spearman,ece_reg,coverage_95
0,gcn,spatial,train,0.040078,0.028123,-0.463246,0.131043,0.115738,NaN,NaN
1,gcn,spatial,val,0.032372,0.022693,-1.578530,0.151064,0.153334,NaN,NaN
2,gcn,spatial,test,0.045858,0.031936,-0.288195,0.103168,0.044109,NaN,NaN

In [2]:
config = load_yaml_config("configs/gnn_config.yaml")
config["model"]["name"] = "gcn"
config["split"]["type"] = "spatial"

In [4]:
metrics_df = pd.read_csv("reports/tables/gnn_metrics.csv")
metrics_df.tail()

,model,split_type,data_split,rmse,mae,r2,pearson,spearman,ece_reg,coverage_95
0,gcn,spatial,train,0.184002,0.178794,-29.843052,0.141005,0.265227,0.185706,1.0
1,gcn,spatial,val,0.176058,0.171851,-75.268951,0.050469,0.041363,0.185138,1.0
2,gcn,spatial,test,0.190149,0.184483,-21.148783,0.207035,0.400163,0.182426,1.0

In [ ]:
import os
os.chdir("..")

import sys
sys.path.append("src")

from wildfire_gnn.pipelines.gnn_pipeline import run_gnn_pipeline
from wildfire_gnn.utils.config import load_yaml_config

config = load_yaml_config("configs/gnn_config.yaml")
metrics = run_gnn_pipeline(config)
metrics

Epoch 001 | Train Loss: 0.013897 | Val Loss: 0.011320
Epoch 002 | Train Loss: 0.013247 | Val Loss: 0.011264
Epoch 003 | Train Loss: 0.012619 | Val Loss: 0.011207
Epoch 004 | Train Loss: 0.012000 | Val Loss: 0.011151
Epoch 005 | Train Loss: 0.011417 | Val Loss: 0.011093
Epoch 006 | Train Loss: 0.010861 | Val Loss: 0.011035
Epoch 007 | Train Loss: 0.010335 | Val Loss: 0.010973
Epoch 008 | Train Loss: 0.009831 | Val Loss: 0.010910
Epoch 009 | Train Loss: 0.009354 | Val Loss: 0.010843
Epoch 010 | Train Loss: 0.008910 | Val Loss: 0.010774
Epoch 011 | Train Loss: 0.008488 | Val Loss: 0.010700
Epoch 012 | Train Loss: 0.008094 | Val Loss: 0.010623
Epoch 013 | Train Loss: 0.007707 | Val Loss: 0.010541
Epoch 014 | Train Loss: 0.007351 | Val Loss: 0.010453
Epoch 015 | Train Loss: 0.007003 | Val Loss: 0.010359
Epoch 016 | Train Loss: 0.006677 | Val Loss: 0.010259
Epoch 017 | Train Loss: 0.006359 | Val Loss: 0.010151
Epoch 018 | Train Loss: 0.006058 | Val Loss: 0.010035
Epoch 019 | Train Loss: 0.005777 | Val Loss: 0.009911
Epoch 020 | Train Loss: 0.005507 | Val Loss: 0.009777
Epoch 021 | Train Loss: 0.005247 | Val Loss: 0.009632
Epoch 022 | Train Loss: 0.004997 | Val Loss: 0.009476
Epoch 023 | Train Loss: 0.004754 | Val Loss: 0.009308
Epoch 024 | Train Loss: 0.004538 | Val Loss: 0.009126
Epoch 025 | Train Loss: 0.004314 | Val Loss: 0.008932
Epoch 026 | Train Loss: 0.004100 | Val Loss: 0.008724
Epoch 027 | Train Loss: 0.003892 | Val Loss: 0.008500
Epoch 028 | Train Loss: 0.003696 | Val Loss: 0.008259
Epoch 029 | Train Loss: 0.003512 | Val Loss: 0.008003
Epoch 030 | Train Loss: 0.003341 | Val Loss: 0.007733
Epoch 031 | Train Loss: 0.003174 | Val Loss: 0.007450
Epoch 032 | Train Loss: 0.003012 | Val Loss: 0.007155
Epoch 033 | Train Loss: 0.002862 | Val Loss: 0.006850
Epoch 034 | Train Loss: 0.002724 | Val Loss: 0.006535
Epoch 035 | Train Loss: 0.002594 | Val Loss: 0.006215
Epoch 036 | Train Loss: 0.002464 | Val Loss: 0.005891
Epoch 037 | Train Loss: 0.002350 | Val Loss: 0.005567
Epoch 038 | Train Loss: 0.002242 | Val Loss: 0.005246
Epoch 039 | Train Loss: 0.002140 | Val Loss: 0.004928
Epoch 040 | Train Loss: 0.002049 | Val Loss: 0.004617
Epoch 041 | Train Loss: 0.001970 | Val Loss: 0.004316
Epoch 042 | Train Loss: 0.001885 | Val Loss: 0.004025
Epoch 043 | Train Loss: 0.001806 | Val Loss: 0.003747
Epoch 044 | Train Loss: 0.001745 | Val Loss: 0.003483
Epoch 045 | Train Loss: 0.001677 | Val Loss: 0.003235
Epoch 046 | Train Loss: 0.001627 | Val Loss: 0.003004
Epoch 047 | Train Loss: 0.001575 | Val Loss: 0.002790
Epoch 048 | Train Loss: 0.001524 | Val Loss: 0.002593
Epoch 049 | Train Loss: 0.001484 | Val Loss: 0.002414
Epoch 050 | Train Loss: 0.001444 | Val Loss: 0.002251
Epoch 051 | Train Loss: 0.001406 | Val Loss: 0.002103
Epoch 052 | Train Loss: 0.001373 | Val Loss: 0.001970
Epoch 053 | Train Loss: 0.001346 | Val Loss: 0.001850
Epoch 054 | Train Loss: 0.001319 | Val Loss: 0.001743
Epoch 055 | Train Loss: 0.001293 | Val Loss: 0.001646
Epoch 056 | Train Loss: 0.001268 | Val Loss: 0.001560
Epoch 057 | Train Loss: 0.001253 | Val Loss: 0.001484
Epoch 058 | Train Loss: 0.001233 | Val Loss: 0.001416
Epoch 059 | Train Loss: 0.001216 | Val Loss: 0.001357
Epoch 060 | Train Loss: 0.001200 | Val Loss: 0.001305
Epoch 061 | Train Loss: 0.001183 | Val Loss: 0.001260
Epoch 062 | Train Loss: 0.001171 | Val Loss: 0.001221
Epoch 063 | Train Loss: 0.001162 | Val Loss: 0.001187
Epoch 064 | Train Loss: 0.001149 | Val Loss: 0.001157
Epoch 065 | Train Loss: 0.001140 | Val Loss: 0.001131
Epoch 066 | Train Loss: 0.001133 | Val Loss: 0.001109
Epoch 067 | Train Loss: 0.001122 | Val Loss: 0.001090
Epoch 068 | Train Loss: 0.001116 | Val Loss: 0.001073
Epoch 069 | Train Loss: 0.001109 | Val Loss: 0.001058
Epoch 070 | Train Loss: 0.001100 | Val Loss: 0.001044
Epoch 071 | Train Loss: 0.001098 | Val Loss: 0.001032
Epoch 072 | Train Loss: 0.001088 | Val Loss: 0.001021
Epoch 073 | Train Loss: 0.001085 | Val Loss: 0.001011
Epoch 074 | Train Loss: 0.001078 | Val Loss: 0.001001
Epoch 075 | Train Loss: 0.001074 | Val Loss: 0.000992
Epoch 076 | Train Loss: 0.001069 | Val Loss: 0.000983
Epoch 077 | Train Loss: 0.001068 | Val Loss: 0.000974
Epoch 078 | Train Loss: 0.001062 | Val Loss: 0.000966
Epoch 079 | Train Loss: 0.001058 | Val Loss: 0.000958
Epoch 080 | Train Loss: 0.001053 | Val Loss: 0.000950
Epoch 081 | Train Loss: 0.001053 | Val Loss: 0.000943
Epoch 082 | Train Loss: 0.001049 | Val Loss: 0.000937
Epoch 083 | Train Loss: 0.001046 | Val Loss: 0.000930
Epoch 084 | Train Loss: 0.001042 | Val Loss: 0.000924
Epoch 085 | Train Loss: 0.001040 | Val Loss: 0.000919
Epoch 086 | Train Loss: 0.001036 | Val Loss: 0.000913
Epoch 087 | Train Loss: 0.001033 | Val Loss: 0.000908
Epoch 088 | Train Loss: 0.001034 | Val Loss: 0.000902
Epoch 089 | Train Loss: 0.001028 | Val Loss: 0.000897
Epoch 090 | Train Loss: 0.001025 | Val Loss: 0.000892
Epoch 091 | Train Loss: 0.001021 | Val Loss: 0.000887
Epoch 092 | Train Loss: 0.001017 | Val Loss: 0.000882
Epoch 093 | Train Loss: 0.001019 | Val Loss: 0.000877
Epoch 094 | Train Loss: 0.001014 | Val Loss: 0.000872
Epoch 095 | Train Loss: 0.001016 | Val Loss: 0.000867
Epoch 096 | Train Loss: 0.001009 | Val Loss: 0.000862
Epoch 097 | Train Loss: 0.001009 | Val Loss: 0.000858
Epoch 098 | Train Loss: 0.001005 | Val Loss: 0.000853
Epoch 099 | Train Loss: 0.001003 | Val Loss: 0.000848
Epoch 100 | Train Loss: 0.001000 | Val Loss: 0.000844
Epoch 101 | Train Loss: 0.001001 | Val Loss: 0.000840

In [1]:
import os
os.chdir("..")

import sys
sys.path.append("src")

from wildfire_gnn.pipelines.gnn_pipeline import run_gnn_pipeline
from wildfire_gnn.utils.config import load_yaml_config

config = load_yaml_config("configs/gnn_config.yaml")
metrics = run_gnn_pipeline(config)
metrics

Epoch 001 | Train Loss: 0.011830 | Val Loss: 0.009903
Epoch 002 | Train Loss: 0.011234 | Val Loss: 0.009833
Epoch 003 | Train Loss: 0.010689 | Val Loss: 0.009764
Epoch 004 | Train Loss: 0.010166 | Val Loss: 0.009695
Epoch 005 | Train Loss: 0.009665 | Val Loss: 0.009625
Epoch 006 | Train Loss: 0.009186 | Val Loss: 0.009554
Epoch 007 | Train Loss: 0.008748 | Val Loss: 0.009480
Epoch 008 | Train Loss: 0.008329 | Val Loss: 0.009404
Epoch 009 | Train Loss: 0.007947 | Val Loss: 0.009324
Epoch 010 | Train Loss: 0.007577 | Val Loss: 0.009240
Epoch 011 | Train Loss: 0.007223 | Val Loss: 0.009152
Epoch 012 | Train Loss: 0.006898 | Val Loss: 0.009059
Epoch 013 | Train Loss: 0.006569 | Val Loss: 0.008960
Epoch 014 | Train Loss: 0.006265 | Val Loss: 0.008855
Epoch 015 | Train Loss: 0.005975 | Val Loss: 0.008743
Epoch 016 | Train Loss: 0.005712 | Val Loss: 0.008624
Epoch 017 | Train Loss: 0.005440 | Val Loss: 0.008498
Epoch 018 | Train Loss: 0.005191 | Val Loss: 0.008365
Epoch 019 | Train Loss: 0.004952 | Val Loss: 0.008223
Epoch 020 | Train Loss: 0.004725 | Val Loss: 0.008074
Epoch 021 | Train Loss: 0.004500 | Val Loss: 0.007916
Epoch 022 | Train Loss: 0.004283 | Val Loss: 0.007751
Epoch 023 | Train Loss: 0.004077 | Val Loss: 0.007576
Epoch 024 | Train Loss: 0.003883 | Val Loss: 0.007394
Epoch 025 | Train Loss: 0.003698 | Val Loss: 0.007202
Epoch 026 | Train Loss: 0.003524 | Val Loss: 0.007003
Epoch 027 | Train Loss: 0.003354 | Val Loss: 0.006796
Epoch 028 | Train Loss: 0.003196 | Val Loss: 0.006581
Epoch 029 | Train Loss: 0.003043 | Val Loss: 0.006359
Epoch 030 | Train Loss: 0.002899 | Val Loss: 0.006131
Epoch 031 | Train Loss: 0.002765 | Val Loss: 0.005896
Epoch 032 | Train Loss: 0.002636 | Val Loss: 0.005656
Epoch 033 | Train Loss: 0.002506 | Val Loss: 0.005413
Epoch 034 | Train Loss: 0.002398 | Val Loss: 0.005168
Epoch 035 | Train Loss: 0.002294 | Val Loss: 0.004922
Epoch 036 | Train Loss: 0.002192 | Val Loss: 0.004676
Epoch 037 | Train Loss: 0.002100 | Val Loss: 0.004433
Epoch 038 | Train Loss: 0.002020 | Val Loss: 0.004194
Epoch 039 | Train Loss: 0.001947 | Val Loss: 0.003959
Epoch 040 | Train Loss: 0.001869 | Val Loss: 0.003732
Epoch 041 | Train Loss: 0.001796 | Val Loss: 0.003512
Epoch 042 | Train Loss: 0.001738 | Val Loss: 0.003301
Epoch 043 | Train Loss: 0.001680 | Val Loss: 0.003100
Epoch 044 | Train Loss: 0.001629 | Val Loss: 0.002910
Epoch 045 | Train Loss: 0.001581 | Val Loss: 0.002731
Epoch 046 | Train Loss: 0.001536 | Val Loss: 0.002565
Epoch 047 | Train Loss: 0.001493 | Val Loss: 0.002409
Epoch 048 | Train Loss: 0.001455 | Val Loss: 0.002266
Epoch 049 | Train Loss: 0.001424 | Val Loss: 0.002134
Epoch 050 | Train Loss: 0.001394 | Val Loss: 0.002014
Epoch 051 | Train Loss: 0.001362 | Val Loss: 0.001904
Epoch 052 | Train Loss: 0.001342 | Val Loss: 0.001804
Epoch 053 | Train Loss: 0.001310 | Val Loss: 0.001714
Epoch 054 | Train Loss: 0.001290 | Val Loss: 0.001633
Epoch 055 | Train Loss: 0.001269 | Val Loss: 0.001560
Epoch 056 | Train Loss: 0.001253 | Val Loss: 0.001494
Epoch 057 | Train Loss: 0.001234 | Val Loss: 0.001435
Epoch 058 | Train Loss: 0.001222 | Val Loss: 0.001383
Epoch 059 | Train Loss: 0.001206 | Val Loss: 0.001336
Epoch 060 | Train Loss: 0.001197 | Val Loss: 0.001294

{'train': {'rmse': 0.03593063658242355,
  'mae': 0.02916707843542099,
  'r2': 0.026688337326049805,
  'pearson': 0.47936972975730896,
  'spearman': 0.5138669543325818,
  'ece_reg': nan,
  'coverage_95': nan},
 'val': {'rmse': 0.03596692895204736,
  'mae': 0.02949337288737297,
  'r2': -0.2105884552001953,
  'pearson': 0.3543436825275421,
  'spearman': 0.3879096427606111,
  'ece_reg': nan,
  'coverage_95': nan},
 'test': {'rmse': 0.03422377841998494,
  'mae': 0.03056255914270878,
  'r2': -3.8866167068481445,
  'pearson': 0.3722684383392334,
  'spearman': 0.4113165555523751,
  'ece_reg': nan,
  'coverage_95': nan}}

In [3]:
import pandas as pd
metrics_df = pd.read_csv("reports/tables/gnn_metrics.csv")
metrics_df.tail()

,run_name,model,split_type,connectivity,fuel_encoding,data_split,rmse,mae,r2,pearson,spearman,ece_reg,coverage_95
0,gnn_recovery_v1,gat,spatial,4,one_hot,train,0.035931,0.029167,0.026688,0.479370,0.513867,NaN,NaN
1,gnn_recovery_v1,gat,spatial,4,one_hot,val,0.035967,0.029493,-0.210588,0.354344,0.387910,NaN,NaN
2,gnn_recovery_v1,gat,spatial,4,one_hot,test,0.034224,0.030563,-3.886617,0.372268,0.411317,NaN,NaN