In [1]:
import os
import sys
sys.path.append("src")

import pandas as pd
import seaborn as sns

from wildfire_gnn.features.feature_analysis import (
    compute_feature_summary,
    plot_feature_distributions,
    compute_feature_target_correlation,
    plot_feature_vs_target,
    compute_split_shift
)

In [5]:
os.chdir("..")
df = pd.read_csv("data/processed/baseline_dataset.csv")
df.head()

,CFL.img,FSP_Index.img,Ignition_Prob.img,Struct_Exp_Index.img,Fuel_Models.img,row_norm,col_norm,target,row_index,col_index
0,0.167812,0.072349,0.096481,0.072349,101.0,0.284360,0.284428,0.019862,540,537
1,0.167812,0.072349,0.096481,0.072349,141.0,0.103739,0.290784,0.023607,197,549
2,0.167812,0.072349,0.096481,0.072349,101.0,0.700369,0.319915,0.052330,1330,604
3,0.167812,0.072349,0.096481,0.072349,121.0,0.091101,0.598517,0.032072,173,1130
4,0.167812,0.072349,0.096481,0.072349,104.0,0.966825,0.660487,0.017760,1836,1247

In [6]:
print("Shape:", df.shape)
df.describe()

Shape: (300000, 10)

,CFL.img,FSP_Index.img,Ignition_Prob.img,Struct_Exp_Index.img,Fuel_Models.img,row_norm,col_norm,target,row_index,col_index
count,3.000000e+05,3.000000e+05,3.000000e+05,3.000000e+05,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000
mean,-3.512800e-09,1.945668e-11,-3.949098e-09,1.945668e-11,137.337023,0.410381,0.376464,0.025153,779.313027,710.763933
std,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,29.096457,0.245783,0.188600,0.033476,466.742473,356.077108
min,-1.118292e+01,-3.003882e+01,-1.830590e+01,-3.003882e+01,91.000000,0.001580,0.001589,0.000023,3.000000,3.000000
25%,1.678120e-01,7.234921e-02,9.648060e-02,7.234921e-02,121.000000,0.204318,0.238877,0.003818,388.000000,451.000000
50%,1.678120e-01,7.234921e-02,9.648060e-02,7.234921e-02,141.000000,0.386519,0.331568,0.012934,734.000000,626.000000
75%,1.678120e-01,7.234921e-02,9.648060e-02,7.234921e-02,161.000000,0.573460,0.484110,0.032171,1089.000000,914.000000
max,1.678120e-01,7.234921e-02,9.648060e-02,7.234921e-02,189.000000,0.998947,0.998411,0.249303,1897.000000,1885.000000

In [ ]:
summary = compute_feature_summary(
    df.drop(columns=["split"]),
    save_path="reports/tables/feature_summary.csv"
)

summary